package com.hemebiotech.analytics;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.List;

public class AnalyticsCounter {

	
	public static void main(String args[]) throws Exception {
		//Input will be generated by ReadSymptomDataFromFile and classed in an HashMap
		HashMap<String, Integer> results = new HashMap<String, Integer>();
		ISymptomReader iSymptomReader = new ReadSymptomDataFromFile("symptoms.txt"); 
		List<String>listOfSymptoms = iSymptomReader.getSymptoms();
		//Counter
		for (int i=0; i<listOfSymptoms.size(); i++) {		
			if (results.containsKey(listOfSymptoms.get(i))) {  //Checking if the String is existing
				int count = 0;
				count = results.get(listOfSymptoms.get(i));
				count++;
				results.put(listOfSymptoms.get(i), count);
			} else {									//If not existing, creating it with count = 1
				results.put(listOfSymptoms.get(i), 1);
			}
		}

		// next generate output 
		try {
		PrintWriter writer = new PrintWriter ("results.out", "UTF-8");
		writer.println(results);
		writer.close();
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
}
